version: '3.9'
services: 

  #PHP Service
  laravel: 
    build: .
    container_name: php-apache
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www/html/
    depends_on: 
      - db
    networks:
      - app-network

  #MySQL Service
  db: 
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: laravels
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/data/:/var/lib/mysql
    networks: 
      - app-network 

networks:
  app-network: 
    driver: bridge