version: '3.9'
services: 

  #PHP
  aplicativo: 
    build: .
    container_name: aplicativo
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
    networks:
      - app-network

  #Nginx
  servidor_web: 
    image: nginx:latest
    container_name: servidor_web
    ports: 
      - "8081:80"
    volumes:
      - ./:/var/www/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/  
    networks: 
      - app-network

  #MySQL
  db: 
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root 
    volumes:
      - ./.docker/data:/var/lib/mysql/ 
    networks: 
      - app-network 

networks:
  app-network: 
    driver: bridge
